"""Validated pack builders plus deterministic ZIP creation and validation."""

from __future__ import annotations

import hashlib
import json
import tempfile
import zipfile
from pathlib import Path, PurePosixPath
from typing import Any

from . import __version__
from .audio import validate_wav, write_kick_wav
from .capabilities import require_capability
from .druiid import GeneratedMidiAsset, generate_midi_essentials
from .manifest import load_manifest, validate_manifest_data, validate_relative_path, write_manifest
from .midi import PPQ, validate_midi, write_chord_midi, write_midi_clip
from .recipe import MidiEssentialsRecipe

ZIP_TIMESTAMP = (1980, 1, 1, 0, 0, 0)


def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for block in iter(lambda: handle.read(65_536), b""):
            digest.update(block)
    return digest.hexdigest()


def _sha256_bytes(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def _key_token(recipe: MidiEssentialsRecipe) -> str:
    root = recipe.root.replace("#", "s")
    quality = "maj" if recipe.scale == "major" else "min"
    return f"{root}{quality}"


def _asset_filename(recipe: MidiEssentialsRecipe, asset: GeneratedMidiAsset) -> str:
    relationship = {"A": "FOUNDATION", "B": "MUTATION_B", "C": "MUTATION_C"}[asset.variation]
    return (
        f"DRUIID_{asset.descriptor}_{relationship}_{recipe.bpm}_{_key_token(recipe)}_"
        f"S{recipe.seed:04d}_V01.mid"
    )


def _validate_midi_entry(path: Path, item: dict[str, Any]) -> dict[str, int | float]:
    metadata = item["metadata"]
    note_range_data = metadata.get("note_range")
    note_range = tuple(note_range_data) if note_range_data is not None else None
    drum_mapping = metadata.get("drum_mapping")
    channel = metadata.get("channel")
    expected_channel = channel - 1 if channel is not None else None
    return validate_midi(
        path,
        expected_bars=metadata["bars"],
        expected_bpm=metadata["tempo_bpm"],
        note_range=note_range,
        drum_mapping=drum_mapping,
        expected_channel=expected_channel,
    )


def _readme_for_midi_pack(pack_name: str, recipe: MidiEssentialsRecipe) -> str:
    return (
        f"# {pack_name}\n\n"
        "A deterministic DRUIID MIDI Essentials pack generated by Abletools. "
        "DRUIID is a provisional musical-behavior profile; no timbral identity is claimed.\n\n"
        f"- Key: {recipe.key}\n"
        f"- Tempo: {recipe.bpm} BPM\n"
        "- Meter: 4/4\n"
        f"- Length: {recipe.bars} bars per clip\n"
        f"- Seed: {recipe.seed}\n"
        f"- Profile: {recipe.profile_version}\n\n"
        "Import the MIDI files from `MIDI/` into Ableton Live. A is the foundation, "
        "B is a restrained mutation, and C is a stronger bounded mutation. "
        "The drum clips use the declared General MIDI mapping on channel 10.\n"
    )


def _write_readme(path: Path, contents: str) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(contents, encoding="utf-8", newline="\n")
    return path


def build_druiid_midi_pack(output: str | Path, recipe: MidiEssentialsRecipe) -> Path:
    """Build, validate, and archive one DRUIID MIDI Essentials pack."""
    require_capability("druiid_midi_essentials")
    require_capability("standard_midi")
    require_capability("zip_pack")
    if recipe.style != "DRUIID":
        raise ValueError("DRUIID MIDI Essentials requires the DRUIID profile")

    root = Path(output)
    midi_dir = root / "MIDI"
    midi_dir.mkdir(parents=True, exist_ok=True)
    pack_name = f"DRUIID_MIDI_ESSENTIALS_{_key_token(recipe)}_S{recipe.seed:04d}"
    _write_readme(root / "README.md", _readme_for_midi_pack(pack_name, recipe))

    files: list[dict[str, Any]] = []
    validations: list[dict[str, Any]] = []
    for asset in generate_midi_essentials(recipe):
        path = write_midi_clip(
            midi_dir / _asset_filename(recipe, asset),
            asset.notes,
            bpm=recipe.bpm,
            bars=recipe.bars,
            track_name=f"DRUIID {asset.role} {asset.variation}",
        )
        relative = path.relative_to(root).as_posix()
        item = {
            "path": relative,
            "role": asset.role,
            "sha256": _sha256(path),
            "format": {"container": "Standard MIDI File", "midi_format": 0, "ppq": PPQ},
            "metadata": asset.metadata,
        }
        result = _validate_midi_entry(path, item)
        files.append(item)
        validations.append({"file": relative, "validator": "abletools.midi", "result": result})

    manifest = {
        "schema_version": "1.0.0",
        "pack_name": pack_name,
        "version": "1.0.0",
        "generator_version": __version__,
        "style": "DRUIID",
        "asset_type": "midi_essentials",
        "seed": recipe.seed,
        "tempo_bpm": recipe.bpm,
        "meter": "4/4",
        "key": recipe.key,
        "root": recipe.root,
        "scale": recipe.scale,
        "bars": recipe.bars,
        "profile_version": recipe.profile_version,
        "recipe": recipe.canonical_data(),
        "files": files,
        "format": {"container": "Standard MIDI File", "midi_format": 0, "ppq": PPQ},
        "generation_notes": [
            "Degree-first, scale-aware DRUIID musical behavior with bounded A/B/C mutation.",
            "No non-deterministic generation stage and no claimed DRUIID timbral profile.",
        ],
        "validation": validations,
        "dependencies": [],
    }
    write_manifest(root / "manifest.json", manifest)
    validate_pack(root)
    archive = write_deterministic_zip(root, root.with_suffix(".zip"))
    validate_zip(archive)
    return root


def build_demo_pack(output: str | Path, seed: int) -> Path:
    """Build the backwards-compatible MIDI/WAV smoke pack under the strict contract."""
    require_capability("standard_midi")
    require_capability("pcm_wav")
    require_capability("zip_pack")
    root = Path(output)
    midi_dir = root / "MIDI"
    wav_dir = root / "WAV"
    midi_path = write_chord_midi(
        midi_dir / f"DRUIID_CHORDS_OPEN_120_Amin_S{seed:04d}_V01.mid",
        [[57, 60, 64, 71], [53, 57, 60, 64], [62, 65, 69, 72], [55, 59, 62, 69]],
        bpm=120,
        bars=8,
        seed=seed,
    )
    wav_path = write_kick_wav(
        wav_dir / f"DRUIID_KICK_COMPACT_S{seed:04d}_V01.wav",
        seed=seed,
    )
    midi_metadata = {
        "bars": 8,
        "chord_symbols": ["Am(add9)", "Fmaj7", "Dm7", "G(add9)"],
        "degree_sequence": [1, 6, 4, 7],
        "key": "A minor",
        "meter": "4/4",
        "non_deterministic_stage": None,
        "profile_version": "DRUIID_R1",
        "role": "chords",
        "root": "A",
        "scale": "minor",
        "seed": seed,
        "tempo_bpm": 120,
    }
    wav_metadata = {
        "channels": 1,
        "duration_seconds": 0.8,
        "non_deterministic_stage": None,
        "role": "kick_one_shot",
        "sample_rate": 48_000,
        "sample_width_bits": 24,
        "seed": seed,
    }
    midi_result = validate_midi(midi_path, expected_bars=8, expected_bpm=120)
    wav_result = validate_wav(wav_path)
    files = [
        {
            "path": midi_path.relative_to(root).as_posix(),
            "role": "chords",
            "sha256": _sha256(midi_path),
            "format": {"container": "Standard MIDI File", "midi_format": 0, "ppq": PPQ},
            "metadata": midi_metadata,
        },
        {
            "path": wav_path.relative_to(root).as_posix(),
            "role": "kick_one_shot",
            "sha256": _sha256(wav_path),
            "format": {"channels": 1, "codec": "PCM", "sample_rate": 48_000, "sample_width_bits": 24},
            "metadata": wav_metadata,
        },
    ]
    manifest = {
        "schema_version": "1.0.0",
        "pack_name": f"DRUIID_DEMO_S{seed:04d}",
        "version": "1.0.0",
        "generator_version": __version__,
        "style": "DRUIID",
        "asset_type": "mixed_demo_pack",
        "seed": seed,
        "tempo_bpm": 120,
        "meter": "4/4",
        "key": "A minor",
        "root": "A",
        "scale": "minor",
        "bars": 8,
        "profile_version": "DRUIID_R1",
        "recipe": {"demo": True, "seed": seed},
        "files": files,
        "format": {"midi": files[0]["format"], "wav": files[1]["format"]},
        "generation_notes": ["Deterministic standard-library reference render."],
        "validation": [
            {"file": files[0]["path"], "validator": "abletools.midi", "result": midi_result},
            {"file": files[1]["path"], "validator": "abletools.audio", "result": wav_result},
        ],
        "dependencies": [],
    }
    _write_readme(
        root / "README.md",
        f"# {manifest['pack_name']}\n\nDeterministic Abletools smoke pack with one MIDI clip and one WAV.\n",
    )
    write_manifest(root / "manifest.json", manifest)
    validate_pack(root)
    archive = write_deterministic_zip(root, root.with_suffix(".zip"))
    validate_zip(archive)
    return root


def validate_pack(root: str | Path) -> dict[str, Any]:
    """Validate a directory pack, its complete inventory, and recorded results."""
    pack_root = Path(root)
    readme = pack_root / "README.md"
    if not readme.is_file() or not readme.read_text(encoding="utf-8").strip():
        raise ValueError("pack requires a non-empty README.md")
    manifest = load_manifest(pack_root / "manifest.json", check_files=True)
    expected_files = {"README.md", "manifest.json", *(item["path"] for item in manifest["files"])}
    actual_files = {
        path.relative_to(pack_root).as_posix()
        for path in pack_root.rglob("*")
        if path.is_file()
    }
    if actual_files != expected_files:
        extra = sorted(actual_files - expected_files)
        missing = sorted(expected_files - actual_files)
        raise ValueError(f"pack inventory mismatch; extra={extra}, missing={missing}")

    recorded = {item["file"]: item for item in manifest["validation"]}
    results: dict[str, Any] = {}
    for item in manifest["files"]:
        path = pack_root.joinpath(*PurePosixPath(item["path"]).parts)
        suffix = path.suffix.lower()
        if suffix in {".mid", ".midi"}:
            validator = "abletools.midi"
            result = _validate_midi_entry(path, item)
        elif suffix == ".wav":
            validator = "abletools.audio"
            result = validate_wav(path)
            if result["sample_rate"] != 48_000 or result["sample_width_bits"] != 24:
                raise ValueError("R1 pack WAV files must be 48 kHz, 24-bit PCM")
        else:
            raise ValueError(f"unsupported enabled asset type: {item['path']}")
        if recorded[item["path"]]["validator"] != validator:
            raise ValueError(f"validation-record validator mismatch: {item['path']}")
        if recorded[item["path"]]["result"] != result:
            raise ValueError(f"stale validation record: {item['path']}")
        results[item["path"]] = result
    return results


def write_deterministic_zip(root: str | Path, archive: str | Path) -> Path:
    """Write a byte-reproducible ZIP after validating the source pack."""
    require_capability("zip_pack")
    pack_root = Path(root)
    manifest = load_manifest(pack_root / "manifest.json", check_files=True)
    validate_pack(pack_root)
    entries = [pack_root / "README.md", pack_root / "manifest.json"] + [
        pack_root.joinpath(*PurePosixPath(item["path"]).parts) for item in manifest["files"]
    ]
    output = Path(archive)
    output.parent.mkdir(parents=True, exist_ok=True)
    with zipfile.ZipFile(output, "w", compression=zipfile.ZIP_STORED) as bundle:
        for path in sorted(entries, key=lambda item: item.relative_to(pack_root).as_posix()):
            relative = path.relative_to(pack_root).as_posix()
            info = zipfile.ZipInfo(f"{manifest['pack_name']}/{relative}", date_time=ZIP_TIMESTAMP)
            info.compress_type = zipfile.ZIP_STORED
            info.create_system = 3
            info.external_attr = 0o100644 << 16
            info.flag_bits = 0x800
            bundle.writestr(info, path.read_bytes())
    return output


def validate_zip(path: str | Path) -> dict[str, Any]:
    """Validate ZIP path safety, exact inventory, checksums, and extracted assets."""
    require_capability("zip_pack")
    archive = Path(path)
    with zipfile.ZipFile(archive, "r") as bundle:
        infos = bundle.infolist()
        names = [info.filename for info in infos]
        if not names or len(names) != len({name.casefold() for name in names}):
            raise ValueError("ZIP must contain a unique, non-empty file inventory")
        for info in infos:
            validate_relative_path(info.filename)
            if info.is_dir():
                raise ValueError("ZIP directory entries are not part of the canonical pack")
            mode = (info.external_attr >> 16) & 0o170000
            if mode == 0o120000:
                raise ValueError("ZIP symbolic links are not allowed")
            if info.flag_bits & 0x1:
                raise ValueError("encrypted ZIP members are not allowed")
        top_levels = {PurePosixPath(name).parts[0] for name in names}
        if len(top_levels) != 1:
            raise ValueError("ZIP must contain exactly one top-level pack directory")
        prefix = next(iter(top_levels))
        manifest_name = f"{prefix}/manifest.json"
        readme_name = f"{prefix}/README.md"
        if manifest_name not in names or readme_name not in names:
            raise ValueError("ZIP requires manifest.json and README.md")
        try:
            manifest = json.loads(bundle.read(manifest_name).decode("utf-8"))
        except (UnicodeDecodeError, json.JSONDecodeError, zipfile.BadZipFile) as error:
            raise ValueError("ZIP contains an unreadable manifest") from error
        validate_manifest_data(manifest)
        if prefix != manifest["pack_name"]:
            raise ValueError("ZIP top-level directory must match manifest pack_name")
        expected = {manifest_name, readme_name} | {
            f"{prefix}/{item['path']}" for item in manifest["files"]
        }
        if set(names) != expected:
            raise ValueError("ZIP inventory does not match its manifest")
        try:
            readme = bundle.read(readme_name).decode("utf-8")
        except (UnicodeDecodeError, zipfile.BadZipFile) as error:
            raise ValueError("ZIP README.md must be non-empty UTF-8 text") from error
        if not readme.strip():
            raise ValueError("ZIP README.md must be non-empty UTF-8 text")
        for item in manifest["files"]:
            member = f"{prefix}/{item['path']}"
            if _sha256_bytes(bundle.read(member)) != item["sha256"]:
                raise ValueError(f"ZIP checksum mismatch: {item['path']}")

        with tempfile.TemporaryDirectory() as directory:
            temporary_root = Path(directory) / prefix
            for name in names:
                destination = Path(directory).joinpath(*PurePosixPath(name).parts)
                destination.parent.mkdir(parents=True, exist_ok=True)
                destination.write_bytes(bundle.read(name))
            results = validate_pack(temporary_root)
    return {"files": len(manifest["files"]), "pack_name": manifest["pack_name"], "result": results}
